# Generated by Django 6.0.3 on 2026-03-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room', models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('office', 'Office/Study'), ('dining', 'Dining Room'), ('garage', 'Garage'), ('other', 'Other')], default='living_room', max_length=50)),
                ('wattage', models.FloatField(help_text='Active wattage in Watts')),
                ('usage_hours_per_day', models.FloatField(help_text='Active usage hours per day')),
                ('standby_enabled', models.BooleanField(default=False)),
                ('standby_wattage', models.FloatField(blank=True, help_text='Standby wattage in Watts (auto-computed if not provided)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
